blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('blog/<int:pk>/', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>/', views.archives, name='archives'),
    path('category/<int:category_id>/', views.category, name='category'),
    path('tag/<int:tag_id>/', views.tag, name='tag'),
]

comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'
urlpatterns = [
    path('comment/<int:post_id>/', views.comment, name='comment'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('<int:pk>/results', views.ResultsView.as_view(), name="results"),
    path('<int:question_id>/vote', views.vote, name="vote")
]

totoyo_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('comments/', include('comments.urls')),
    path('polls/', include('polls.urls')),
    path('', include('blog.urls'), name='home'),
    path('admin/', admin.site.urls),
]

blog/models.py
import markdown
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse
from django.utils import timezone
from django.utils.html import strip_tags


class Category(models.Model):
    class Meta:
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    class Meta:
        verbose_name = '文章'
        verbose_name_plural = verbose_name
        ordering = ['-created_at']

    title = models.CharField('标题', max_length=100)
    body = models.TextField('正文')
    abstract = models.CharField('摘要', max_length=200, blank=True)
    category = models.ForeignKey(Category, verbose_name='分类', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag, verbose_name='标签', blank=True)
    author = models.ForeignKey(User, verbose_name='作者', on_delete=models.CASCADE)
    created_at = models.DateTimeField('创建时间', default=timezone.now)
    updated_at = models.DateTimeField('更新时间')

    def save(self, *args, **kwargs):
        self.updated_at = timezone.now()

        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
        ])
        self.abstract = strip_tags(md.convert(self.body))[:54]
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

comments/models.py
from django.db import models
from django.utils import timezone


class Comment(models.Model):
    name = models.CharField('名字', max_length=50)
    email = models.EmailField('邮箱')
    url = models.URLField('网址', blank=True)
    text = models.TextField('内容')
    created_at = models.DateTimeField('创建时间', default=timezone.now)
    post = models.ForeignKey('blog.Post', verbose_name='文章', on_delete=models.CASCADE)

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{} : {}'.format(self.name, self.text[:20])

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    class Meta:
        verbose_name = '问题'
        verbose_name_plural = verbose_name

    question_text = models.CharField(max_length=20)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=20)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

comments/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

blog/views.py
import re

from django.shortcuts import render, get_object_or_404

from blog.models import Post, Category, Tag

import markdown


def index(request):
    post_list = Post.objects.all().order_by('-created_at')
    return render(request, 'blog/index.html', context={
        'post_list': post_list,
    })


def archives(request, year, month):
    post_list = Post.objects.filter(created_at__year=year, created_at__month=month).order_by('-created_at')
    return render(request, 'blog/index.html', context={
        'post_list': post_list,
    })


def category(request, category_id):
    cate = get_object_or_404(Category, pk=category_id)
    post_list = Post.objects.filter(category=cate).order_by('-created_at')
    return render(request, 'blog/index.html', context={
        'post_list': post_list
    })


def tag(request, tag_id):
    tg = get_object_or_404(Tag, pk=tag_id)
    post_list = Post.objects.filter(tags=tg).order_by('-created_at')
    return render(request, 'blog/index.html', context={
        'post_list': post_list,
    })


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    post.body = md.convert(post.body)

    m = re.search(r'<div class="toc">\s*<ul>(.*)</ul>\s*</div>', md.toc, re.S)
    post.toc = m.group(1) if m is not None else ''

    return render(request, 'blog/detail.html', context={
        'post': post,
    })

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.views.decorators.http import require_POST

from blog.models import Post
from comments.forms import CommentForm


@require_POST
def comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    form = CommentForm(request.POST)

    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

        return redirect(post)

    context = {
        'post': post,
        'form': form,
    }
    print(context)
    return render(request, 'comments/preview.html', context=context)

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
# Create your views here.
from django.urls import reverse
from django.views import generic

from polls.models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

# 使用通用视图代替
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {
#         'latest_question_list': latest_question_list,
#     }
#     return render(request, 'polls/index.html', context)
#
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})
#
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

blog/templates/blog/base.html
{% load static %}
{% load blog_extras %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ToToYo Blog</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'blog/css/clean-blog.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
        <a class="navbar-brand" href="#">ToToYo Blog</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:index' %}">首页</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="about.html">推荐文章</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="post.html">关于我</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="contact.html">联系我</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Header -->
{% block header %}
{% endblock header %}

<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {% block container %}
            {% endblock container %}
        </div>
        <div class="col-lg-4 col-md-2">
            {% block toc %}
            {% endblock toc %}

            {% show_recent_posts %}
            {% show_categories %}
            {% show_archives %}
            {% show_tags %}
        </div>
    </div>
</div>

<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'blog/js/clean-blog.min.js' %}"></script>

<script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
<script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
<script>
    hljs.initHighlightingOnLoad();
    hljs.initLineNumbersOnLoad();
</script>

</body>

</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load comments_extras %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/highlight.custom.css' %}">
{% block header %}
    <header class="masthead" style="background-image: url({% static 'blog/img/post-bg.jpg' %})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="post-heading">
                        <h1>{{ post.title }}</h1>
                        <h2 class="subheading">{{ post.abstract }}</h2>
                        <span class="meta">作者
              <a href="#">{{ post.author.get_username }}</a>
               发布于 {{ post.created_at }}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}
{% block container %}
    <p>{{ post.body|safe }}</p>
    <hr>
    <p><h3>添加评论</h3></p>
    {% show_comment_form post %}
{% endblock container %}
{% block toc %}
{% endblock toc %}

blog/templates/blog/inclusions/_archives.html
<div class="widget widget-archives">
    <h3 class="widget-title">归档</h3>
    <ul>
        {% for date in date_list %}
            <li>
                <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
            </li>
        {% empty %}
            暂无归档
        {% endfor %}
    </ul>
</div>

blog/templates/blog/inclusions/_categories.html
<div class="widget widget-category">
    <h3 class="widget-title">分类</h3>
    <ul>
        {% for category in category_list %}
            <li>
                <a href="{% url 'blog:category' category.id %}">{{ category.name }} <span class="post-count">(13)</span></a>
            </li>
        {% empty %}
            暂无分类
        {% endfor %}
    </ul>
</div>

blog/templates/blog/inclusions/_recent_posts.html
<div class="widget widget-recent-posts">
    <h3 class="widget-title">最新文章</h3>
    <ul>
        {% for post in recent_post_list %}
            <li>
                <a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a>
            </li>
        {% empty %}
            暂无文章
        {% endfor %}
    </ul>
</div>

blog/templates/blog/inclusions/_tags.html
<div class="widget widget-tag-cloud">
    <h3 class="widget-title">标签</h3>
    <ul>
        {% for tag in tag_list %}
            <li>
                <a href="{% url 'blog:tag' tag.id %}">{{ tag.name }}</a>
            </li>
        {% endfor %}
    </ul>
</div>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block header %}
    <header class="masthead" style="background-image: url({% static 'blog/img/home-bg.jpg' %})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Banner</h1>
                        <span class="subheading">The Emperor's New Banner</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}

{% block container %}
    {% for post in post_list %}
        <div class="post-preview">
            <a href="{% url 'blog:detail' post.id %}">
                <h2 class="post-title">
                    {{ post.title }}
                </h2>
                <h3 class="post-subtitle">
                    {{ post.abstract }}
                </h3>
            </a>
            <p class="post-meta">作者：
                <a href="#">{{ post.author.get_username }}</a>
                发布于 {{ post.created_at }}</p>
        </div>
        <hr>
    {% empty %}
        <div class="post-preview">
            <h3 class="post-subtitle">暂无数据</h3>
        </div>
    {% endfor %}
    <div class="clearfix">
        <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
    </div>
{% endblock container %}

comments/templates/comments/inclusions/_form.html
<form name="sentMessage" id="contactForm" novalidate="" action="{% url 'comments:comment' post.pk %}" method="post">
    {% csrf_token %}
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label for="{{ form.name.id_for_label }}">{{ form.name.label }}</label>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
            {{ form.email }}
            {{ form.name.errors }}
        </div>
    </div>
    <div class="control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
            <label for="{{ form.url.id_for_label }}">{{ from.url.label }}</label>
            {{ form.url }}
            {{ form.name.url }}
        </div>
    </div>
    <div class="control-group">
        <div class="form-group floating-label-form-group controls">
            <label for="{{ form.text.id_for_label }}">{{ form.text.label }}</label>
            {{ form.text }}
            {{ form.text.errors }}
        </div>
    </div>
    <br>
    <div id="success"></div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary" id="sendMessageButton">发表</button>
    </div>
</form>

comments/templates/comments/preview.html
{% extends 'blog/base.html' %}
{% load static %}
{% load comments_extras %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/css/highlight.custom.css' %}">
{% block header %}
    <header class="masthead" style="background-image: url({% static 'blog/img/post-bg.jpg' %})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="post-heading">
                        <h1>{{ post.title }}</h1>
                        <h2 class="subheading">{{ post.abstract }}</h2>
                        <span class="meta">作者
              <a href="#">{{ post.author.get_username }}</a>
               发布于 {{ post.created_at }}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock header %}
{% block container %}
    <p>{{ post.body|safe }}</p>
    <hr>
    <p><h3>添加评论</h3></p>
    {% show_comment_form post %}
{% endblock container %}
{% block toc %}
{% endblock toc %}

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ question.question_text }}</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <br>
    {% endfor %}
    <input type="submit" value="投票">
</form>
</body>
</html>

polls/templates/polls/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}

    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>结果</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote Again?</a>
</body>
</html>